services:
  postgres:
    image: postgres:16.3
    container_name: publisher-web-service-db-test
    hostname: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: publisher_web_service_db_test
    ports:
      - "5432:5432"
  infrastructure:
    image: ghcr.io/wozut/publisher-infrastructure:latest
    container_name: publisher-infrastructure
    hostname: infrastructure
    environment:
      PORT: 8080
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: publisher_web_service_db_test
    depends_on:
      postgres:
        condition: service_started
