package tcla.contexts.tcla.webapi.springweb.organization.checkwhetherorganizationcanhaveonemoreteam.jsonapi

data class CheckWhetherOrganizationCanHaveOneMoreTeamDocument(
    val data: CheckWhetherOrganizationCanHaveOneMoreTeamResource
)
