package tcla.contexts.tcla.core.domain.question.model


sealed class Question(
    val id: QuestionId,
    val label: Label,
    val order: Order
) {
    sealed class Label(val value: String) {
        data object Gender : Label("Which of the following describes how you think of yourself?")
        data object WorkFamiliarity : Label("I am familiar with the work I am currently doing")
        data object TeamFamiliarity : Label("I am familiar with the team I am currently working with")
        data object ModeOfWorking : Label("What is your main mode of working?")
        data object Q1TeamCompositionComplexity1 : Label("There are multiple stakeholder groups with differing expectations")
        data object Q1TeamCompositionComplexity2 : Label("There is a complex team structure with varying competencies")
        data object Q1TeamCompositionComplexity3 : Label("There are different working and discipline-related backgrounds among members")
        data object Q2TeamCompositionCompetence1 : Label("The current skill mix is responding to the work demand")
        data object Q2TeamCompositionCompetence2 : Label("People have the right level of experience to succeed")
        data object Q2TeamCompositionCompetence3 : Label("We have the right knowledge, skills, and abilities within the team")
        data object Q3MemberRolesRoleClarity1 : Label("Roles and responsibilities are clearly defined")
        data object Q3MemberRolesRoleClarity2 : Label("I know exactly what is expected of me")
        data object Q3MemberRolesRoleClarity3 : Label("I know how to divide my time")
        data object Q4MemberRolesRoleFit1 : Label("I feel confident about the particular strengths I bring to the table")
        data object Q4MemberRolesRoleFit2 : Label("I feel competent and fully able to handle my job")
        data object Q4MemberRolesRoleFit3 : Label("I feel that my job and I are well matched")
        data object Q5MemberRolesRoleLoad1 : Label("I don't have any free time on my hands")
        data object Q5MemberRolesRoleLoad2 : Label("I often feel under time pressure")
        data object Q5MemberRolesRoleLoad3 : Label("I have too many things to take care of")
        data object Q6CultureTeamAlignment1 : Label("We are strongly committed to a common goal(s)")
        data object Q6CultureTeamAlignment2 : Label("Members have a shared sense of ownership around success")
        data object Q6CultureTeamAlignment3 : Label("People jointly take ownership of how things get done")
        data object Q7CultureTeamInteractionCommunication1 : Label("We communicate enough")
        data object Q7CultureTeamInteractionCommunication2 : Label("We have clear communication paths - we know who to talk to/ask for what")
        data object Q7CultureTeamInteractionCommunication3 : Label("Team meetings are focused")
        data object Q8CultureTeamInteractionKnowledgeExchange1 : Label("Team members promote knowledge sharing")
        data object Q8CultureTeamInteractionKnowledgeExchange2 : Label("Team members view knowledge exchange and integration as important")
        data object Q8CultureTeamInteractionKnowledgeExchange3 : Label("People share their knowledge and expertise with one another")
        data object Q9CultureMemberPsychologicalSafetyAuthenticity1 : Label("I feel confident in expressing my true self without fear of being judged")
        data object Q9CultureMemberPsychologicalSafetyAuthenticity2 : Label("I feel like my colleagues understand who I really am")
        data object Q9CultureMemberPsychologicalSafetyAuthenticity3 : Label("I don't feel pressured to behave in certain ways")
        data object Q10CultureMemberPsychologicalSafetySpeakingUp1 : Label("I feel comfortable speaking up about difficult issues and problems")
        data object Q10CultureMemberPsychologicalSafetySpeakingUp2 : Label("When I speak up, people listen")
        data object Q10CultureMemberPsychologicalSafetySpeakingUp3 : Label("I feel able to challenge the status-quo")
        data object Q11CultureMemberPsychologicalSafetyEmbracingFailure1 : Label("I am not afraid to make mistakes")
        data object Q11CultureMemberPsychologicalSafetyEmbracingFailure2 : Label("I feel able to share my weaknesses/mistakes")
        data object Q11CultureMemberPsychologicalSafetyEmbracingFailure3 : Label("I feel comfortable asking others for help when I struggle")
        data object Q12UseOfInformation1 : Label("Information is reliable")
        data object Q12UseOfInformation2 : Label("Information is relevant and to the point")
        data object Q12UseOfInformation3 : Label("Information is accessible")
        data object Q13EfficiencyAndEffectivenessProcess1 : Label("Our work processes are effective")
        data object Q13EfficiencyAndEffectivenessProcess2 : Label("Documentation and transparency is adequate")
        data object Q13EfficiencyAndEffectivenessProcess3 : Label("Team members work to ensure we are using the best practice methods")
        data object Q14EfficiencyAndEffectivenessConsistency1 : Label("Work processes are consistent")
        data object Q14EfficiencyAndEffectivenessConsistency2 : Label("We have common ways of working")
        data object Q14EfficiencyAndEffectivenessConsistency3 : Label("We are aligned on \"how we do things\"")
        data object Q15EfficiencyAndEffectivenessPace1 : Label("We get stuff done quickly")
        data object Q15EfficiencyAndEffectivenessPace2 : Label("We are not wasting time over some unimportant activities")
        data object Q15EfficiencyAndEffectivenessPace3 : Label("Causes of delay to delivery are proactively identified and removed")
        data object Q16EfficiencyAndEffectivenessPerformance1 : Label("We consistently produce strong, measurable results")
        data object Q16EfficiencyAndEffectivenessPerformance2 : Label("Stakeholders compliment us with the value that we deliver to them")
        data object Q16EfficiencyAndEffectivenessPerformance3 : Label("Stakeholders are generally happy with how the team responds to their needs")
        data object Q17AdaptabilityResilience1 : Label("When things fail, failures are easy to fix")
        data object Q17AdaptabilityResilience2 : Label("We have the necessary logs to understand why things failed")
        data object Q17AdaptabilityResilience3 : Label("We address and resolve issues quickly")
        data object Q18AdaptabilityIterativeWorking1 : Label("There is continuous feedback and improvement of processes")
        data object Q18AdaptabilityIterativeWorking2 : Label("We regularly reserve time to improve working methods")
        data object Q18AdaptabilityIterativeWorking3 : Label("We regularly share iterations with stakeholders, making changes along the way")
        data object Q19AdaptabilityContinuousLearning1 : Label("Members see learning as a part of their work")
        data object Q19AdaptabilityContinuousLearning2 : Label("Members consciously learn through daily collaboration and problem solving")
        data object Q19AdaptabilityContinuousLearning3 : Label("People are encouraged to learn new skills, techniques or practices")
        data object Q20ProblemStatementProblemDefinition1 : Label("Problems we work on are defined in a concise manner")
        data object Q20ProblemStatementProblemDefinition2 : Label("There is a shared understanding of the problem/opportunity")
        data object Q20ProblemStatementProblemDefinition3 : Label("The problem/opportunity can be explained in a clear and straightforward way")
        data object Q21ProblemStatementSolutionAlignment1 : Label("It is clear, what the result will look like once the solution is implemented")
        data object Q21ProblemStatementSolutionAlignment2 : Label("There is a good understanding of expectations on what has to be delivered")
        data object Q21ProblemStatementSolutionAlignment3 : Label("There is clarity what success means")
        data object Q22ComplexityTask1 : Label("Tasks require a lot of thought and problem-solving")
        data object Q22ComplexityTask2 : Label("There are a lot of complex dependencies between tasks")
        data object Q22ComplexityTask3 : Label("Tasks have a high degree of uncertainty")
        data object Q22ComplexityTask4 : Label("Tasks are very challenging/mentally demanding")
        data object Q23ComplexityContextual1 : Label("Contextual influences (may) change requirement")
        data object Q23ComplexityContextual2 : Label("Stakeholder requirements (may) unexpectedly change")
        data object Q23ComplexityContextual3 : Label("External circumstances (e.g. regulatory, political, market) are uncertain")
        data object Q23ComplexityContextual4 : Label("Unexpected \"interruptions\" are (or may be) disrupting progress")
        data object Q24Metrics1 : Label("We are using clearly defined real-time metrics to assess our work")
        data object Q24Metrics2 : Label("We are consistently monitoring results using these metrics")
        data object Q24Metrics3 : Label("Success metrics are clear to all stakeholders")
        data object Q25ToolsSuitability1 : Label("We use tools that are suited (fit for purpose)")
        data object Q25ToolsSuitability2 : Label("Tools have all the functionality needed to complete the work")
        data object Q25ToolsSuitability3 : Label("There is a good understanding on how to use the tools needed to complete the work")
        data object Q25ToolsSuitability4 : Label("Tools are well integrated, avoiding redundant and/or manual work")
        data object Q26ToolsPerformance1 : Label("Tools are performing well")
        data object Q26ToolsPerformance2 : Label("Tools perform in a reliable and accurate manner")
        data object Q26ToolsPerformance3 : Label("The tools we use are stable")
        data object Q26ToolsPerformance4 : Label("Tools or systems are continuously responsive; no (minor) delays")
        data object Q27Environment1 : Label("There are no significant physical hazards at work")
        data object Q27Environment2 : Label("I am comfortable at my workplace")
        data object Q27Environment3 : Label("My physical work environment suits my needs")
        data object Q27Environment4 : Label("There is no exposure to distracting noise and/or vibration")
    }
}
